Repository 2110336-2565-2/sec2-group10-demo-frontend, pull requests merged in 2023-02, with the labels that each got.

#1 DEMO 41 - Shared: Setup MUI theme
  .prettierrc.json
  README.md
  next.config.js
  package.json
  pnpm-lock.yaml
  src/app/head.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  src/styles/Home.module.css
  src/styles/globals.css
  src/theme/index.ts
  src/theme/typography.ts
Labels: ready to review, ready to merge

#6 DEMO 43 - Shared: NextAuth
  .env.development
  .env.production
  .gitignore
  package.json
  pnpm-lock.yaml
  src/configs/index.ts
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].ts
Labels: ready for review

#13 DEMO 33 - 5: RegisterForm
  .github/workflows/vercel-pr.yaml
  package.json
  pnpm-lock.yaml
  src/assets/demo-logo.svg
  src/components/RegisterForm/index.tsx
  src/theme/index.ts
Labels: ready to merge

#11 Demo 42 - Shared: Setup Axios
  .env.development
  package.json
  pnpm-lock.yaml
  src/services/apiAxios.ts
Labels: ready for review

#12 Demo-35: loginForm component
  package.json
  pnpm-lock.yaml
  src/components/LoginForm.tsx
Labels: ready for review, ready to merge

#14 DEMO 39 - Shared: MusicPlayer
  next.config.js
  package.json
  pnpm-lock.yaml
  src/components/MusicPlayer/MusicControl.tsx
  src/components/MusicPlayer/MusicTimeLine.tsx
  src/components/MusicPlayer/SoundControl.tsx
  src/components/MusicPlayer/index.tsx
  src/hooks/useSound.tsx
  src/pages/test.tsx
  src/stores/musicPlayerStore.ts
  src/theme/index.ts
Labels: ready for review

#17 Demo 32
  .env.development
  .env.production
  src/components/Navbar/Navbar.tsx
  src/components/RegisterForm/index.tsx
  src/pages/signup.tsx
  src/services/apiAxios.ts
Labels: ready to merge

#19 DEMO-34:login page
  src/components/Button.tsx
  src/components/LoginForm.tsx
  src/components/Navbar/Navbar.tsx
  src/components/RegisterForm/index.tsx
  src/pages/home.tsx
  src/pages/login.tsx
Labels: ready for review, ready to merge

#20 DEMO 40 - Shared: MusicPlayerFullSize
  src/components/MusicPlayer/FullSizeContent.tsx
  src/components/MusicPlayer/MusicControl.tsx
  src/components/MusicPlayer/MusicTimeLine.tsx
  src/components/MusicPlayer/SoundControl.tsx
  src/components/MusicPlayer/index.tsx
  src/hooks/useShow.tsx
  src/layout/DesktopLoayput.tsx
Labels: ready for review

#21 Fix: auth
  src/components/LoginForm.tsx
  src/components/Navbar/Navbar.tsx
  src/components/RegisterForm/index.tsx
  src/pages/api/auth/[...nextauth].ts
Labels: ready for review

#23 Update/navbar
  src/components/Navbar/Navbar.tsx
Labels: ready for review, ready to merge

#26 DEMO 69 - (FrontEnd) 19: Playlists/[name] page, playlist title
  src/components/EditableImage/index.tsx
  src/components/EditableTypography/index.tsx
  src/pages/playlists/[playlistId].tsx
  src/theme/index.ts
Labels: ready for review

#25 feat:playlist component
  src/components/Playlist.tsx
Labels: ready for review
